function [methodinfo,structs,enuminfo,ThunkLibName]=lib_prototype
%LIB_PROTOTYPE Create structures to define interfaces found in 'lib_linux_test'.

%This function was generated by loadlibrary.m parser version  on Sat Feb 20 23:20:11 2016
%perl options:'lib_linux_test.i -outfile=lib_prototype.m -thunkfile=lib_linux_test_thunk_glnxa64.c -header=lib_linux_test.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'lib_linux_test_thunk_glnxa64');
% extern double multiply ( double x , double y ); 
fcns.thunkname{fcnNum}='doubledoubledoubleThunk';fcns.name{fcnNum}='multiply'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='double'; fcns.RHS{fcnNum}={'double', 'double'};fcnNum=fcnNum+1;
methodinfo=fcns;